<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>icon.png</PackageIcon>
    <ApplicationIcon>Assets\Images\icon.ico</ApplicationIcon>
	<Version>1.0</Version>
	<AssemblyVersion>1.0.0</AssemblyVersion>  
	<FileVersion>1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\Images\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Fonts\" />
  </ItemGroup>
	
  <ItemGroup>
	  <None Update="Assets\Sounds\**\*.wav">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Images\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>